### ISSUE TITLE
support .tofu files

### ISSUE THREAD

**Issue by carnei-ro** [tofuutils/pre-commit-opentofu#6]
### What problem are you facing?

OpenTofu 1.8.0 has been released. Now it is possible to have `.tofu` files instead of `.tf` files. 

### How could pre-commit-opentofu help solve your problem?

I'd like to be able to use the pre-commit rules on those new `.tofu` files.

**Comment by joelmccoy** [comment]
would also very much like to see this :)

**Comment by kvendingoldo** [comment]
This issue has been resolved in version 2.1.0 :tada:

**Comment by muffl0n** [comment]
I'm still getting an empty `README.md` with modules containing `.tofu` files. Does this work for somebody?

It feels like there's still some work to be done in `terraform-docs`: https://github.com/terraform-docs/terraform-docs/issues/811

**Comment by samuelberntzen** [comment]
> I'm still getting an empty `README.md` with modules containing `.tofu` files. Does this work for somebody?
> 
> It feels like there's still some work to be done in `terraform-docs`: [terraform-docs/terraform-docs#811](https://github.com/terraform-docs/terraform-docs/issues/811)

I am also just getting an empty `README.md`. I guess `.tofu` files arent fully support yet in terraform-docs?

**Comment by RoseSecurity** [comment]
Is this repository actively maintained? I'll gladly step in and assist if there is any interest in additional contributors

**Comment by kvendingoldo** [comment]
@RoseSecurity I’d be glad if you could help us maintain it. Right now, we’re focused on tenv, so support with side projects like this would be really valuable.

**Comment by RoseSecurity** [comment]
> [@RoseSecurity](https://github.com/RoseSecurity) I’d be glad if you could help us maintain it. Right now, we’re focused on tenv, so support with side projects like this would be really valuable.

I'm here to help! Just opened my [first PR](https://github.com/tofuutils/pre-commit-opentofu/pull/74) with some pre-commit fixes and updates along with expanded `.tofu` support

**Comment by kvendingoldo** [comment]
This issue has been resolved in version 2.4.0 :tada:

**Comment by kvendingoldo** [comment]
@RoseSecurity if you’d like, I’d be happy to make you a maintainer of pre-commit-opentofu. We don’t have enough time to maintain it properly right now, so any help would be really appreciated.
